config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  root to: 'dashboard#index'

  resources :products do
    member do
      post :toggle_state
      post :accept_offer
      get :destroy_confirm
    end

    resources :bids, only: [:new, :create]
  end

  resources :bids, only: :create do
    post :approve, on: :member
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bid.rb
# frozen_string_literal: true

class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :product, presence: true
  validates :user, presence: true

  validate :overbid, on: :create
  validate :insufficient_funds, on: :create

  before_create :destroy_previous_bid
  after_create :charge
  after_create :mark_product
  after_destroy :refund

  delegate :email, to: :user, prefix: true

  private

  # callbacks

  def destroy_previous_bid
    return unless bid = product.reload.bid
    bid.destroy
  end

  def charge
    user.with_lock do
      user.update_attribute :balance, user.balance - amount
    end
  end

  def mark_product
    product.update_attribute(:state, 'under_offer')
  end

  def refund
    user.with_lock do
      user.update_attribute :balance, user.balance + amount
    end
  end

  # validations

  def overbid
    return unless product
    return unless (product.reload.bid_amount && amount <= product.bid_amount.to_f) || amount < product.price
    errors.add(:amount, 'should be equal or higher than current bid')
  end

  def insufficient_funds
    return unless user && amount > user.balance
    errors.add(:user, 'Has insufficient balance')
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  extend Enumerize

  belongs_to :user

  has_one :bid, dependent: :destroy, validate: true

  validates_associated :bid
  validates :user, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  scope :available_for_auction, ->(user) { includes(:bid).where.not(user_id: user, state: %i[hidden sold]) }
  scope :by_user, ->(user) { where(user_id: user) }
  scope :bid_by, ->(user) { includes(:bid).where(bids: { user_id: user }) }
  scope :won_by, ->(user) { includes(:bid).where(bids: { user_id: user, state: :accepted }) }
  scope :ordered, ->{ order(updated_at: :desc) }

  enumerize :state, in: %i[hidden published under_offer sold]

  delegate :amount, to: :bid, prefix: true, allow_nil: :true
  delegate :user, to: :bid, prefix: true, allow_nil: :true

  def self.filtered(filter)
    return all unless Product.state.values.include?(filter)
    where(state: filter)
  end

  def toggle_state
    case state
    when 'hidden' then update_attribute(:state, :published)
    when 'published' then update_attribute(:state, :hidden)
    else nil
    end
  end

  def accept_offer
    user.with_lock do
      user.update_attribute :balance, user.balance + bid_amount
      bid.update_attribute :state, :accepted
      update_attribute(:state, 'sold')
    end
  end

  def allowed_to_update?
    %w[published hidden].include?(state)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :bids,     dependent: :destroy
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
  end

  def create
    @bid = Bid.new(bid_params)

    if @bid.save
      redirect_to root_path, format: 'js'
    else
      render 'create'
    end
  end

  private

  def bid_params
    params.require(:bid)
          .permit(:amount)
          .merge(user_id: current_user.id, product_id: params[:product_id])
  end
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :filtered

  def index; end

  private

  def filtered
    return @products = Product.won_by(current_user).decorate if params[:filter] == 'won'

    @products = Product.available_for_auction(current_user).ordered
    @products = @products.bid_by(current_user) if params[:filter] == 'my_bids'
    @products = @products.decorate
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: %i[edit update toggle_state accept_offer destroy]

  def index
    @products = current_user.products
      .includes(:bid)
      .by_user(current_user)
      .filtered(params[:filter]).decorate
  end

  def create
    @product = current_user.products.build(product_attributes)

    if @product.save
      redirect_to products_path, format: 'js'
    else
      render 'create'
    end
  end

  def edit
  end

  def update
    if @product.allowed_to_update? && @product.update(product_attributes)
      redirect_to products_path, format: 'js'
    else
      render 'update'
    end
  end

  def toggle_state
    @product.toggle_state

    redirect_to products_path
  end

  def accept_offer
    @product.accept_offer

    redirect_to products_path
  end

  def destroy
    @product.allowed_to_update? && @product.destroy

    redirect_to products_path, format: 'js'
  end

  private

  def product_attributes
    params.require(:product).permit(:name, :description, :price)
  end

  def find_product
    @product = current_user.products.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def current_user_balance
    return unless signed_in?
    current_user.decorate.balance
  end
end

app/helpers/bids_helper.rb
# frozen_string_literal: true

module BidsHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def toggle_state_link(product)
    title, btn_class =\
     case product.state
     when 'hidden' then ['Publish', 'btn-primary']
     when 'published' then ['Hide from search', 'btn-danger']
     when 'under_offer' then accept_offer(product)
     when 'sold' then ['Sold', 'btn-secondary disabled']
     end

    link_to title, toggle_state_product_path(product), class: "btn #{btn_class}", method: :post
  end

  def accept_offer(product)
    link_to 'Accept', accept_offer_product_path(product), class: 'btn btn-success', method: :post
  end
end

app/views/bids/_errors.haml
.alert.alert-danger
  = pluralize(@bid.errors.count, 'error')
  prohibited this bid from being saved:
  %ul
    - @bid.errors.full_messages.each do |msg|
      %li="* #{msg}"

app/views/bids/_form.haml
= simple_form_for [product, Bid.new], remote: true do |f|
  #bid_errors

  = f.input :amount, as: :decimal
  = f.button :submit, 'Send', class: 'btn btn-primary'

app/views/bids/create.js.erb
$('#bid_errors').html("<%= j render 'errors' %>")

app/views/bids/new.js.erb
$("#bid-modal .modal-body").html("<%= j render 'form', product: @product %>");
$("#bid-modal").modal('show');
Forms.initCheckbox(".modal");

app/views/dashboard/_list.haml
- if signed_in?
  %ul#products-list.nav.nav-tabs{role: "tablist"}
    %li.nav-item
      = link_to 'All', root_path, class: "nav-link #{'active' unless params[:filter]}"
    %li.nav-item
      = link_to 'My bids', root_path(filter: 'my_bids'), class: "nav-link #{'active' if params[:filter] == 'my_bids'}"
    %li.nav-item
      = link_to 'Won', root_path(filter: 'won'), class: "nav-link #{'active' if params[:filter] == 'won'}"

- if @products.any?
  - @products.each do |product|
    .card.product
      .card-body
        %span.badge.badge-warning.float-right= product.user.email

        %h5.card-title= product.name
        %p.card-text= product.description

        - if signed_in? && product.bid_user == current_user
          %span.badge.badge-pill.badge-danger= 'Your bid'

      .card-footer
        = product.price
        = product.bid_link
- else
  = 'There are no products yet'

app/views/dashboard/index.haml
.row
  .col-md-9
    = render 'shared/head'
    = render 'list'
  .col-md-3
    = current_user_balance

= render 'shared/modal', title: 'New bid', id: 'bid-modal'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Auction
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.7.2/css/all.css", :integrity => "sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr", :rel => "stylesheet"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-dark.bg-primary
      = link_to 'Auction', root_path, class: 'navbar-brand'
      - if signed_in?
        %span.navbar-brand= current_user.email
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-lg active nav-link float-right', role: 'button'
      - else
        = link_to 'Sign in', new_user_session_path, class: 'btn btn-primary btn-lg active nav-link float-right', role: 'button'

    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    .container{style: 'padding: 10px'}
      = yield

app/views/products/_errors.haml
.alert.alert-danger
  = pluralize(@product.errors.count, 'error')
  prohibited this product from being saved:
  %ul
    - @product.errors.full_messages.each do |msg|
      %li="* #{msg}"

app/views/products/_filter.haml
%ul#products-list.nav.nav-tabs{role: "tablist"}
  %li.nav-item
    = link_to 'All', products_path, class: "nav-link #{'active' unless params[:filter]}"
  %li.nav-item
    = link_to 'Published', products_path(filter: 'published'), class: "nav-link #{'active' if params[:filter] == 'published'}"
  %li.nav-item
    = link_to 'Under offer', products_path(filter: 'under_offer'), class: "nav-link #{'active' if params[:filter] == 'under_offer'}"
  %li.nav-item
    = link_to 'Sold', products_path(filter: 'sold'), class: "nav-link #{'active' if params[:filter] == 'sold'}"
  %li.nav-item
    = link_to 'Hidden', products_path(filter: 'hidden'), class: "nav-link #{'active' if params[:filter] == 'hidden'}"

app/views/products/_form.haml
= simple_form_for product, remote: true do |f|
  #product_errors

  = f.input :name
  = f.input :description
  = f.input :price, as: :decimal

  = f.button :submit, 'Send', class: 'btn btn-primary'

app/views/products/_list.haml
= render 'filter'

- if @products.any?
  - @products.each do |product|
    .card.product
      .card-body
        - if product.state.hidden? || product.state.published?
          = link_to product_path(product), method: :delete, class: 'float-right', data: { confirm: 'Are you sure?' } do
            %i.fas.fa-trash-alt

          = link_to edit_product_path(product), remote: true, class: 'float-right' do
            %i.fas.fa-pencil-alt
        - else
          %span.badge.badge-warning.float-right= product.bid.user_email

        %h5.card-title= product.name
        %p.card-text= product.description

      .card-footer
        = product.price
        = product.toggle_state_link
- else
  = 'There are no products yet'

app/views/products/create.js.erb
$('#product_errors').html("<%= j render 'errors' %>")

app/views/products/edit.js.erb
$("#edit-modal .modal-body").html("<%= j render 'form', product: @product %>");
$("#edit-modal").modal('show');
Forms.initCheckbox(".modal");

app/views/products/index.haml
.row
  .col-md-9
    = render 'shared/head'
    = render 'list'
  .col-md-3
    = current_user.decorate.balance
    %button.btn.btn-primary{"data-target" => '#new-modal', 'data-toggle' => 'modal', type: 'button'}
      Add product

= render 'shared/modal', title: 'New product', id: 'new-modal' do
  = render 'products/form', product: Product.new

= render 'shared/modal', title: 'Edit product', id: 'edit-modal'

app/views/products/update.js.erb
$('#product_errors').html("<%= j render 'errors' %>")

app/views/shared/_head.haml
- if signed_in?
  %ul.nav.nav-pills.nav-fill.general
    %li.nav-item
      = link_to 'Auction', root_path, class: "nav-link #{'active' if params[:controller] == 'dashboard'}"
    %li.nav-item
      = link_to 'My products', products_path, class: "nav-link #{'active' if params[:controller] == 'products'}"

app/views/shared/_modal.haml
.modal.fade{'aria-hidden' => 'true', 'aria-labelledby' => 'new-modal-label', role: 'dialog', tabindex: '-1', id: id}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#new-modal-label.modal-title= title
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = yield